### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Kflash** [gotwarlost/istanbul#633] opened 2016-05-22 13:31 UTC
Is this project dead?

**Comment by fizker** [comment] 2016-05-22 13:33
Duplicate of #624

**Comment by graingert** [comment] 2016-06-21 09:59
@gotwarlost it's late june now

**Comment by gotwarlost** [comment] 2016-06-21 10:50
Yes, I'm working on it :) see https://github.com/istanbuljs/istanbul-lib-instrument/issues/4

**Comment by gotwarlost** [comment] 2016-06-29 10:55
No. Maybe yes. Depends on your point of view. Stay tuned for some announcements soon.

**Closed by gotwarlost** 2016-06-29 10:55 UTC

**Comment by graingert** [comment] 2016-06-29 10:58
![fawkesburngif](https://cloud.githubusercontent.com/assets/413772/16449677/b4d34f80-3df0-11e6-9977-66575c89bc5a.gif)
